version: '3'

volumes:
  oracle-db-data:

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:23.3.0.0
    environment:
      - 'ORACLE_PWD=superSecretPassword1!'
    ports:
      - '1521:1521'
    volumes:
      - 'oracle-db-data:/opt/oracle/oradata'
      - './docker:/opt/oracle/scripts/startup:ro'
