ALTER SESSION SET CONTAINER=FREEPDB1;
CREATE USER IF NOT EXISTS etutor IDENTIFIED BY "etutor-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO etutor;

-- Creating diagnose1 to diagnose5 users
CREATE USER IF NOT EXISTS diagnose1 IDENTIFIED BY "diagnose1-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO diagnose1;

CREATE USER IF NOT EXISTS diagnose2 IDENTIFIED BY "diagnose2-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO diagnose2;

CREATE USER IF NOT EXISTS diagnose3 IDENTIFIED BY "diagnose3-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO diagnose3;

CREATE USER IF NOT EXISTS diagnose4 IDENTIFIED BY "diagnose4-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO diagnose4;

CREATE USER IF NOT EXISTS diagnose5 IDENTIFIED BY "diagnose5-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO diagnose5;

-- Creating submit1 to submit5 users
CREATE USER IF NOT EXISTS submit1 IDENTIFIED BY "submit1-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO submit1;

CREATE USER IF NOT EXISTS submit2 IDENTIFIED BY "submit2-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO submit2;

CREATE USER IF NOT EXISTS submit3 IDENTIFIED BY "submit3-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO submit3;

CREATE USER IF NOT EXISTS submit4 IDENTIFIED BY "submit4-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO submit4;

CREATE USER IF NOT EXISTS submit5 IDENTIFIED BY "submit5-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO submit5;

exit;
