ALTER SESSION SET CONTAINER=FREEPDB1;
CREATE USER IF NOT EXISTS etutor IDENTIFIED BY "etutor-secret" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO etutor;
exit;
